apiVersion: kmm.sigs.x-k8s.io/v1beta1
kind: Module
metadata:
  name: ice
spec:
  moduleLoader:
    serviceAccountName: default
    container:
      modprobe:
        moduleName: ice
        dirName: /opt 
      kernelMappings:  
        - regexp: '^.+$'
          containerImage: image-registry.openshift-image-registry.svc:5000/build-driver/ice:latest
  selector:
    node-role.kubernetes.io/master: ""
